import {
  FilePlus2, Link2, Handshake, FolderOpen, ClipboardList, Plus, Download,
  FolderCog, FileStack, Shuffle, Repeat, BookOpen, Bookmark, ImagePlus,
  FileText, Scissors, Divide, FileX2, FileType, Box, Target, Search,
  Trash2, X, Dices, CircleOff, Hammer, Paperclip, ImageIcon, Files,
  ArrowUpDown, Hash, MoveHorizontal, Square, FileEdit, Copy, FolderTree,
  RotateCcw, ScanLine, Package, TrendingDown, Zap, Rocket, Flame,
  Briefcase, Settings, Globe, Mail, Smartphone, BarChart3, Triangle,
  Gift, Printer, Wrench, HardDrive, Shield, Eye, Code, ZoomIn,
  TrendingUp, Sparkles, Eraser, CircleArrowDown, Type, FileCode,
  FileSpreadsheet, Presentation, FileChartColumn, FileImage, Image,
  Palette, Theater, FileInput, FileOutput, FileArchive, Brush,
  Lock, Unlock, Key, ShieldCheck, Archive, EyeOff, LockOpen,
  FileKey, MailCheck, FileLock, BadgeCheck, Fingerprint, UserCheck,
  ShieldAlert, ShieldQuestion, AlertCircle, Pencil, Edit, Edit3,
  FileSignature, PenTool, Stamp, Droplet, Droplets, Sticker, Tag,
  Tags, Layers, Sparkle, ListOrdered, AlignLeft, AlignCenter,
  AlignRight, FileDigit, Binary, ArrowUpCircle, LayoutTemplate,
  CheckCircle, Circle, MessageSquare, Highlighter, Crop, Maximize2,
  SquareArrowOutUpRight, SlidersHorizontal, Clock, BookOpenText, Minimize2,
  Filter, Grid3x3, RotateCw, Move, PaintBucket, Contrast, Blend,
  StickyNote, Bug, List, CalendarClock, Save, Speaker, Braces,
  Sigma, Gauge, Menu, FileJson, FileBarChart, FileSliders,
  ChevronDown, AlignJustify, Video, Send, Database, Share2,
  SplitSquareVertical, FileWarning, Network, Ban, QrCode,
  MoveRight, BadgeAlert, BadgeInfo, Info, Minimize,  Maximize,
  ChartLine, SquareDashed, RadioTower, TextCursorInput,
  Combine, Sliders, ReplaceAll, Upload, Aperture, Link,
  Images, Table, Table2, DatabaseZap, FileCheck, FormInput,
  FileSearch, Receipt, FileCode2, Brackets, TableProperties,
  GitCompare, FileDiff, ScanSearch,
  type LucideIcon
} from "lucide-react";

export const toolIcons: Record<string, LucideIcon> = {
  // Merge & Combine tools
  "merge-pdf": FilePlus2,
  "combine-pdf": Link2,
  "join-pdf-files": Handshake,
  "pdf-merger": FolderOpen,
  "pdf-combiner": ClipboardList,
  "append-pdf": Plus,
  "add-pdf-to-pdf": Download,
  "merge-multiple-pdfs": FolderCog,
  "combine-pdf-pages": FileStack,
  "merge-pdf-alternately": Shuffle,
  "interleave-pdf": Repeat,
  "pdf-binder": BookOpen,
  "merge-pdf-bookmarks": Bookmark,
  "combine-pdf-images": ImagePlus,
  "merge-pdf-word": FileText,

  // Split & Extract tools
  "split-pdf": Scissors,
  "pdf-splitter": Divide,
  "divide-pdf": Divide,
  "break-pdf": FileX2,
  "split-pdf-by-pages": FileType,
  "split-pdf-by-size": Box,
  "split-pdf-by-bookmarks": Bookmark,
  "split-pdf-by-text": Type,
  "split-pdf-in-half": Divide,
  "split-pdf-every-x-pages": Files,
  "extract-pdf-pages": Target,
  "pdf-page-extractor": Search,
  "delete-pdf-pages": Trash2,
  "pdf-page-remover": X,
  "extract-specific-pages": Dices,
  "split-pdf-odd-pages": CircleOff,
  "split-pdf-even-pages": Circle,
  "pdf-breaker": Hammer,
  "extract-pdf-attachments": Paperclip,
  "extract-pdf-images": ImageIcon,

  // Organize & Edit tools
  "organize-pdf-pages": Files,
  "reorder-pdf-pages": ArrowUpDown,
  "sort-pdf-pages": Hash,
  "move-pdf-pages": MoveHorizontal,
  "insert-blank-page": Square,
  "add-pages-to-pdf": FileEdit,
  "duplicate-pdf-pages": Copy,
  "pdf-page-manager": FolderTree,
  "reverse-pdf-pages": RotateCcw,
  "scan-to-pdf": ScanLine,

  // Compress & Optimize tools
  "compress-pdf": Package,
  "pdf-compressor": Package,
  "reduce-pdf-size": TrendingDown,
  "optimize-pdf": Zap,
  "pdf-optimizer": Rocket,
  "high-compression-pdf": Flame,
  "basic-compression-pdf": Briefcase,
  "custom-pdf-compression": Settings,
  "compress-pdf-for-web": Globe,
  "compress-pdf-for-email": Mail,
  "compress-scanned-pdf": Smartphone,
  "pdf-size-reducer": BarChart3,
  "shrink-pdf": Triangle,
  "pdf-file-compressor": Gift,
  "optimize-pdf-for-print": Printer,

  // Repair & Fix tools
  "repair-pdf": Wrench,
  "fix-pdf": Wrench,
  "recover-pdf-data": HardDrive,
  "repair-corrupt-pdf": Shield,
  "pdf-repair-tool": Hammer,

  // OCR & Extract tools
  "ocr-pdf": Eye,
  "scanned-pdf-to-text": Code,
  "pdf-ocr": Search,
  "searchable-pdf-creator": ZoomIn,
  "ocr-to-word": FileText,
  "ocr-to-excel": FileSpreadsheet,
  "image-to-text": ImageIcon,
  "linearize-pdf": TrendingUp,
  "pdf-fast-web-view": Zap,
  "pdf-optimizer-remove-unused": Eraser,
  "downsample-pdf-images": CircleArrowDown,
  "pdf-font-subsetter": Type,

  // Convert tools
  "word-to-pdf": FileText,
  "doc-to-pdf": FileText,
  "docx-to-pdf": FileText,
  "powerpoint-to-pdf": Presentation,
  "ppt-to-pdf": FileChartColumn,
  "pptx-to-pdf": Presentation,
  "excel-to-pdf": FileSpreadsheet,
  "xls-to-pdf": FileSpreadsheet,
  "xlsx-to-pdf": FileSpreadsheet,
  "jpg-to-pdf": FileImage,
  "png-to-pdf": Image,
  "bmp-to-pdf": Palette,
  "gif-to-pdf": Theater,
  "pdf-to-word": FileOutput,
  "pdf-to-doc": FileOutput,
  "pdf-to-docx": FileOutput,
  "pdf-to-excel": FileOutput,
  "pdf-to-xls": FileOutput,
  "pdf-to-xlsx": FileOutput,
  "pdf-to-powerpoint": FileOutput,
  "pdf-to-ppt": FileOutput,
  "pdf-to-pptx": FileOutput,
  "pdf-to-jpg": FileOutput,
  "pdf-to-png": FileOutput,
  "pdf-to-bmp": FileOutput,
  "pdf-to-gif": FileOutput,
  "pdf-to-tiff": FileOutput,
  "pdf-to-html": Code,
  "pdf-to-xml": FileCode,
  "pdf-to-csv": FileSpreadsheet,
  "pdf-to-txt": FileText,
  "tiff-to-pdf": FileInput,
  "html-to-pdf": FileInput,
  "xml-to-pdf": FileInput,
  "csv-to-pdf": FileInput,
  "txt-to-pdf": FileInput,
  "epub-to-pdf": FileInput,
  "mobi-to-pdf": FileInput,
  "rtf-to-pdf": FileInput,
  "odt-to-pdf": FileInput,
  "ods-to-pdf": FileInput,
  "odp-to-pdf": FileInput,
  "svg-to-pdf": FileInput,
  "webp-to-pdf": FileInput,
  "heic-to-pdf": FileInput,
  "djvu-to-pdf": FileInput,
  "cbr-to-pdf": FileArchive,
  "cbz-to-pdf": FileArchive,
  "ps-to-pdf": FileInput,
  "eps-to-pdf": FileInput,
  "xps-to-pdf": FileInput,
  "oxps-to-pdf": FileInput,

  // Security tools - Encryption
  "protect-pdf": Lock,
  "encrypt-pdf": Lock,
  "secure-pdf": ShieldCheck,
  "password-protect-pdf": Key,
  "add-password-to-pdf": LockOpen,
  "unlock-pdf": Unlock,
  "remove-password-pdf": LockOpen,
  "decrypt-pdf": Unlock,
  "pdf-password-remover": Unlock,
  "protect-pdf-editing": Lock,
  "protect-pdf-printing": Printer,
  "pdf-permissions": FileKey,
  "watermark-protection": Droplet,
  "drm-protection": ShieldAlert,
  "batch-protect-pdf": FolderTree,
  "secure-pdf-sharing": MailCheck,
  "pdf-viewer-protection": EyeOff,
  "pdf-copy-protection": FileLock,
  "restrict-pdf-permissions": Lock,
  
  // Security tools - Signature
  "sign-pdf": Pencil,
  "esign-pdf": FileSignature,
  "digital-signature-pdf": BadgeCheck,
  "electronic-signature": Edit,
  "add-signature-to-pdf": Edit3,
  "certify-pdf": CheckCircle,
  "validate-pdf-signature": ShieldCheck,
  "remove-pdf-signature": X,
  "verify-pdf-signature": ShieldQuestion,
  "timestamp-pdf": AlertCircle,
  "batch-sign-pdf": FolderTree,
  "bulk-esign-pdf": FileSignature,
  "multi-signature-pdf": UserCheck,

  // Security tools - Watermark
  "watermark-pdf": Droplet,
  "text-watermark-pdf": Type,
  "image-watermark-pdf": ImageIcon,
  "diagonal-watermark-pdf": Brush,
  "tiled-watermark-pdf": Layers,
  "transparent-watermark-pdf": Droplets,
  "custom-watermark-pdf": Palette,
  "remove-watermark-pdf": Eraser,
  "batch-watermark-pdf": FolderTree,

  // Security tools - Stamp
  "stamp-pdf": Stamp,
  "confidential-stamp-pdf": ShieldAlert,
  "draft-stamp-pdf": FileEdit,
  "approved-stamp-pdf": CheckCircle,
  "custom-stamp-pdf": Sticker,

  // Edit Pages tools - Page Numbers
  "add-page-numbers": ListOrdered,
  "number-pdf-pages": Hash,
  "custom-page-numbering": Settings,
  "bates-numbering-pdf": Binary,
  "roman-numeral-pages": FileDigit,
  "remove-page-numbers": Eraser,
  
  // Edit Pages tools - Headers & Footers
  "add-header-pdf": ArrowUpCircle,
  "add-footer-pdf": CircleArrowDown,
  "custom-header-footer": Settings,
  "left-aligned-header": AlignLeft,
  "center-aligned-header": AlignCenter,
  "right-aligned-header": AlignRight,
  "remove-header-footer": Eraser,

  // Edit Pages tools - Overlay
  "overlay-pdf": LayoutTemplate,
  "pdf-overlay": LayoutTemplate,

  // Page Numbers, Headers & Footers - Additional
  "add-bates-numbering": Binary,
  "add-bates-stamp": Tag,
  "add-page-numbers-roman": FileDigit,
  "add-page-numbers-start-at-x": ListOrdered,
  "add-header-to-pdf": ArrowUpCircle,
  "add-footer-to-pdf": CircleArrowDown,
  "add-header-and-footer": LayoutTemplate,
  "add-header-date-time": Clock,
  "add-footer-page-x-of-y": Hash,
  "remove-pdf-header": Eraser,
  "remove-pdf-footer": Eraser,
  "pdf-page-numbering": ListOrdered,

  // Watermark & Stamp tools - Additional
  "add-image-watermark": ImageIcon,
  "add-text-watermark": Type,
  "add-tiled-watermark": Grid3x3,
  "remove-watermark-from-pdf": Eraser,
  "pdf-watermark-remover": Eraser,
  "pdf-watermarker": Droplet,
  "pdf-watermark-pdf": Droplet,
  "add-confidential-stamp": ShieldAlert,
  "add-draft-stamp": FileEdit,
  "custom-pdf-stamp": Sticker,
  "pdf-stamper": Stamp,

  // Editor & Annotation tools
  "edit-pdf": Pencil,
  "pdf-editor": Edit,
  "edit-pdf-text": Type,
  "edit-pdf-metadata": Settings,
  "pdf-metadata-editor": SlidersHorizontal,
  "annotate-pdf": MessageSquare,
  "pdf-annotator": MessageSquare,
  "add-comments-to-pdf": MessageSquare,
  "pdf-commenter": MessageSquare,
  "pdf-comment-summarizer": List,
  "highlight-pdf-text": Highlighter,
  "strikethrough-pdf-text": Eraser,
  "underline-pdf-text": Edit3,
  "draw-on-pdf": Brush,
  "pdf-marker": PenTool,
  "add-shapes-to-pdf": Circle,
  "add-text-to-pdf": Type,
  "add-image-to-pdf": ImagePlus,
  "replace-image-in-pdf": ReplaceAll,
  "add-hyperlink-to-pdf": Link,
  "add-timestamp-to-pdf": Clock,

  // Crop, Resize & Layout tools
  "crop-pdf": Crop,
  "pdf-cropper": Crop,
  "crop-pdf-margins": Maximize2,
  "auto-crop-pdf-margins": Minimize2,
  "resize-pdf": Maximize,
  "pdf-resizer": SplitSquareVertical,
  "change-pdf-page-size": Sliders,
  "pdf-to-a4": FileText,
  "pdf-to-letter": FileText,
  "change-pdf-layout": LayoutTemplate,
  "add-gutter-margins-to-pdf": MoveHorizontal,
  "auto-deskew-pdf": RotateCw,
  "n-up-pdf": Grid3x3,

  // Color & Visual tools
  "invert-pdf-colors": Contrast,
  "pdf-color-inverter": Palette,
  "pdf-color-changer": PaintBucket,
  "pdf-to-grayscale": Filter,
  "pdf-to-black-white": Contrast,

  // Security tools - Additional
  "pdf-unlocker": Unlock,
  "remove-pdf-password": LockOpen,
  "pdf-security": ShieldCheck,
  "pdf-protector": Lock,
  "pdf-locker": FileLock,
  "pdf-encryptor": Lock,
  "add-pdf-permissions": FileKey,
  "set-pdf-permissions": Settings,
  "disable-pdf-copying": Ban,
  "disable-pdf-editing": Lock,
  "disable-pdf-printing": Printer,

  // Signature tools - Additional
  "pdf-signer": FileSignature,
  "pdf-signature-tool": Edit3,
  "request-pdf-signature": Send,
  "pdf-signature-remover": X,
  "pdf-digital-signature-validator": BadgeCheck,

  // Flatten & Optimize tools
  "flatten-pdf": Layers,
  "flatten-pdf-comments": MessageSquare,
  "flatten-pdf-layers": Layers,
  "sanitize-pdf": ShieldCheck,

  // Redact & Security
  "redact-pdf": EyeOff,
  "pdf-redactor": ShieldAlert,
  "blackout-pdf": Ban,
  "remove-pdf-metadata": Eraser,
  "change-pdf-metadata": Settings,

  // Bookmarks & Links
  "pdf-bookmark-creator": Bookmark,
  "pdf-bookmark-editor": Edit,
  "pdf-bookmark-remover": X,
  "pdf-link-editor": Link,
  "pdf-link-checker": Search,
  "pdf-link-remover": X,

  // Advanced PDF Editors
  "pdf-object-editor": Database,
  "pdf-path-editor": Network,
  "pdf-javascript-editor": Code,
  "pdf-javascript-remover": X,
  "pdf-action-remover": Trash2,
  "pdf-annotation-remover": MessageSquare,
  "pdf-font-finder": Search,
  "pdf-font-replacer": Type,
  "pdf-initial-view-editor": Eye,
  "pdf-page-labeler": Tag,
  "pdf-page-inverter": RotateCw,
  "pdf-certificate-adder": BadgeCheck,

  // PDF Creation & Presentation
  "create-pdf": FilePlus2,
  "pdf-creator": Save,
  "pdf-booklet-maker": BookOpen,
  "pdf-handout-maker-6-up": Grid3x3,
  "pdf-presentation-maker": Presentation,
  "impose-pdf": LayoutTemplate,

  // Conversion tools - Additional formats
  "pdf-to-images": ImageIcon,
  "images-to-pdf": ImagePlus,
  "pdf-to-text": FileText,
  "pdf-to-json": FileJson,
  "pdf-to-svg": Image,
  "pdf-to-eps": FileOutput,
  "pdf-to-postscript": FileOutput,
  "postscript-to-pdf": FileInput,
  "pdf-to-pdf-a": Archive,
  "pdf-to-searchable": Search,
  "pdf-to-dwg": FileInput,
  "pdf-to-dxf": FileInput,
  "dwg-to-pdf": FileInput,
  "dxf-to-pdf": FileInput,
  "ai-to-pdf": Palette,
  "psd-to-pdf": Image,
  "visio-to-pdf": FileInput,
  "vsd-to-pdf": FileInput,
  "publisher-to-pdf": FileInput,
  "pub-to-pdf": FileInput,
  "indd-to-pdf": FileInput,
  "keynote-to-pdf": Presentation,
  "pages-to-pdf": FileText,
  "numbers-to-pdf": FileSpreadsheet,
  "latex-to-pdf": Code,
  "tex-to-pdf": Code,
  "markdown-to-pdf": FileCode,
  "md-to-pdf": FileCode,
  "pdf-to-markdown": FileOutput,
  "pdf-to-md": FileOutput,
  "url-to-pdf": Globe,
  "webpage-to-pdf": SquareArrowOutUpRight,
  "email-to-pdf": Mail,
  "eml-to-pdf": Mail,
  "msg-to-pdf": Mail,
  "mpp-to-pdf": FileBarChart,
  "wpd-to-pdf": FileText,
  "pdf-to-wpd": FileOutput,

  // PDF to Office formats - Advanced
  "pdf-to-docx-ocr": FileOutput,
  "pdf-to-odt-ocr": FileOutput,
  "pdf-to-txt-ocr": FileText,
  "pdf-to-word-flowing": FileOutput,
  "pdf-to-word-layout": FileOutput,
  "pdf-to-ppt-editable": Presentation,
  "pdf-to-ppt-images": Presentation,
  "pdf-to-epub": FileOutput,
  "pdf-to-epub-ocr": FileOutput,
  "pdf-to-mobi": FileOutput,
  "pdf-to-rtf": FileOutput,
  "pdf-to-odt": FileOutput,
  "pdf-to-ods": FileOutput,
  "pdf-to-odp": FileOutput,
  "pdf-to-xps": FileOutput,
  "pdf-to-keynote": Presentation,
  "pdf-to-pages": FileText,
  "pdf-to-numbers": FileSpreadsheet,

  // PDF Image Formats
  "pdf-to-png-transparent": ImageIcon,
  "pdf-to-webp": ImageIcon,
  "pdf-to-tiff-multipage": FileImage,

  // PDF Advanced Features
  "pdf-to-speech": Speaker,
  "pdf-to-mp3": Speaker,
  "pdf-to-multi-page-html": Code,
  "pdf-to-single-page-html": Code,

  // PDF Converter (generic)
  "pdf-converter": Shuffle,

  // Watermark & Stamp Tools (New)
  "pdf-underlay": Layers,
  "pdf-stamp-datetime": CalendarClock,
  "pdf-stamp-username": UserCheck,
  "pdf-bates-numbering-advanced": Hash,

  // Data Extraction Tools (New)
  "extract-text-from-pdf": TextCursorInput,
  "pdf-text-extractor": FileText,
  "extract-images-from-pdf": Image,
  "pdf-image-extractor": Images,
  "extract-tables-from-pdf": Table,
  "pdf-table-extractor": Table2,
  "extract-data-from-pdf": Database,
  "pdf-data-extractor": DatabaseZap,
  "extract-fonts-from-pdf": Type,

  // PDF Converter Tools (New)
  "pdf-to-excel-converter": FileSpreadsheet,
  "pdf-to-csv-converter": FileCode,

  // PDF Form Tools (New)
  "fill-pdf-forms": FileInput,
  "pdf-form-filler": FileCheck,
  "create-fillable-pdf": FilePlus2,
  "pdf-form-creator": FormInput,
  "extract-pdf-form-data": FileOutput,
  "read-pdf-form-data": FileSearch,
  "flatten-pdf-form": Lock,
  "pdf-form-data-to-csv": FileSpreadsheet,
  "pdf-form-data-to-xml": FileCode,
  "pdf-form-data-to-json": Braces,
  "pdf-form-filler-csv": FileInput,
  "pdf-form-filler-json": FileJson,
  "pdf-form-data-export-csv": TableProperties,
  "pdf-form-data-export-json": Package,

  // Invoice & Business Tools (New)
  "pdf-zugferd-invoice-extractor": Receipt,
  "pdf-to-ubl-xml": FileCode2,

  // PDF Viewer Tools (New)
  "pdf-viewer": Eye,
  "pdf-reader": BookOpen,
  "open-pdf": FolderOpen,
  "read-pdf-online": Globe,

  // PDF Analysis Tools (New)
  "compare-pdf": GitCompare,
  "pdf-comparer": FileDiff,
  "pdf-difference-checker": ScanSearch,

  // Comparison Tools (40 New Tools)
  "compare-pdf-text": FileDiff,
  "compare-pdf-visual": GitCompare,
  "pdf-analyzer": ScanSearch,
  "get-pdf-info": BadgeInfo,
  "count-pdf-pages": Hash,
  "pdf-word-counter": TextCursorInput,
  "pdf-character-counter": Type,
  "detect-pdf-fonts": Type,
  "check-pdf-a-compliance": ShieldCheck,
  "validate-pdf-a": CheckCircle,
  "pdf-previewer": Eye,
  "pdf-page-counter": ListOrdered,
  "compare-pdf-side-by-side": GitCompare,
  "compare-pdf-overlay": Layers,
  "pdf-a-validator": ShieldCheck,
  
  // PDF/A Conversion Tools
  "pdf-to-pdf-a-1a": Archive,
  "pdf-to-pdf-a-1b": Archive,
  "pdf-to-pdf-a-2a": Archive,
  "pdf-to-pdf-a-2b": Archive,
  "pdf-to-pdf-a-2u": Archive,
  "pdf-to-pdf-a-3a": Archive,
  "pdf-to-pdf-a-3b": Archive,
  "pdf-to-pdf-a-3u": Archive,
  
  // PDF/X Tools
  "pdf-x-validator": Printer,
  "pdf-to-pdf-x-1a": Printer,
  "pdf-to-pdf-x-3": Printer,
  "pdf-to-pdf-x-4": Printer,
  
  // Other Standards
  "pdf-to-pdf-e": Settings,
  "pdf-to-pdf-ua": UserCheck,
  
  // Accessibility Tools
  "pdf-accessibility-checker": ShieldCheck,
  "pdf-tagger": Tags,
  "pdf-read-order-editor": ListOrdered,
  "add-alt-text-pdf": ImagePlus,
  "pdf-language-setter": Globe,
  "pdf-to-tagged-pdf": Tags,
  
  // Print Production Tools
  "pdf-color-separations-viewer": Layers,
  "pdf-ink-coverage-calculator": Droplet,
  "pdf-transparency-flattener": Layers,
  "pdf-overprint-preview": Eye,
  "pdf-hairline-fixer": Pencil,

  // Default icon for any unmapped tools
  default: FileText,
};

export function getToolIcon(toolId: string): LucideIcon {
  return toolIcons[toolId] || toolIcons.default;
}
