import {
  FilePlus2, Link2, Handshake, FolderOpen, ClipboardList, Plus, Download,
  FolderCog, FileStack, Shuffle, Repeat, BookOpen, Bookmark, ImagePlus,
  FileText, Scissors, Divide, FileX2, FileType, Box, Target, Search,
  Trash2, X, Dices, CircleOff, Hammer, Paperclip, ImageIcon, Files,
  ArrowUpDown, Hash, MoveHorizontal, Square, FileEdit, Copy, FolderTree,
  RotateCcw, ScanLine, Package, TrendingDown, Zap, Rocket, Flame,
  Briefcase, Settings, Globe, Mail, Smartphone, BarChart3, Triangle,
  Gift, Printer, Wrench, HardDrive, Shield, Eye, Code, ZoomIn,
  TrendingUp, Sparkles, Eraser, CircleArrowDown, Type, FileCode,
  FileSpreadsheet, Presentation, FileChartColumn, FileImage, Image,
  Palette, Theater, FileInput, FileOutput, FileArchive, Brush,
  Lock, Unlock, Key, ShieldCheck, Archive, EyeOff, LockOpen,
  FileKey, MailCheck, FileLock, BadgeCheck, Fingerprint, UserCheck,
  ShieldAlert, ShieldQuestion, AlertCircle, Pencil, Edit, Edit3,
  FileSignature, PenTool, Stamp, Droplet, Droplets, Sticker, Tag,
  Tags, Layers, Sparkle, ListOrdered, AlignLeft, AlignCenter,
  AlignRight, FileDigit, Binary, ArrowUpCircle, LayoutTemplate,
  CheckCircle, Circle, type LucideIcon
} from "lucide-react";

export const toolIcons: Record<string, LucideIcon> = {
  // Merge & Combine tools
  "merge-pdf": FilePlus2,
  "combine-pdf": Link2,
  "join-pdf-files": Handshake,
  "pdf-merger": FolderOpen,
  "pdf-combiner": ClipboardList,
  "append-pdf": Plus,
  "add-pdf-to-pdf": Download,
  "merge-multiple-pdfs": FolderCog,
  "combine-pdf-pages": FileStack,
  "merge-pdf-alternately": Shuffle,
  "interleave-pdf": Repeat,
  "pdf-binder": BookOpen,
  "merge-pdf-bookmarks": Bookmark,
  "combine-pdf-images": ImagePlus,
  "merge-pdf-word": FileText,

  // Split & Extract tools
  "split-pdf": Scissors,
  "pdf-splitter": Divide,
  "divide-pdf": Divide,
  "break-pdf": FileX2,
  "split-pdf-by-pages": FileType,
  "split-pdf-by-size": Box,
  "split-pdf-by-bookmarks": Bookmark,
  "split-pdf-by-text": Type,
  "split-pdf-in-half": Divide,
  "split-pdf-every-x-pages": Files,
  "extract-pdf-pages": Target,
  "pdf-page-extractor": Search,
  "delete-pdf-pages": Trash2,
  "pdf-page-remover": X,
  "extract-specific-pages": Dices,
  "split-pdf-odd-pages": CircleOff,
  "split-pdf-even-pages": Circle,
  "pdf-breaker": Hammer,
  "extract-pdf-attachments": Paperclip,
  "extract-pdf-images": ImageIcon,

  // Organize & Edit tools
  "organize-pdf-pages": Files,
  "reorder-pdf-pages": ArrowUpDown,
  "sort-pdf-pages": Hash,
  "move-pdf-pages": MoveHorizontal,
  "insert-blank-page": Square,
  "add-pages-to-pdf": FileEdit,
  "duplicate-pdf-pages": Copy,
  "pdf-page-manager": FolderTree,
  "reverse-pdf-pages": RotateCcw,
  "scan-to-pdf": ScanLine,

  // Compress & Optimize tools
  "compress-pdf": Package,
  "pdf-compressor": Package,
  "reduce-pdf-size": TrendingDown,
  "optimize-pdf": Zap,
  "pdf-optimizer": Rocket,
  "high-compression-pdf": Flame,
  "basic-compression-pdf": Briefcase,
  "custom-pdf-compression": Settings,
  "compress-pdf-for-web": Globe,
  "compress-pdf-for-email": Mail,
  "compress-scanned-pdf": Smartphone,
  "pdf-size-reducer": BarChart3,
  "shrink-pdf": Triangle,
  "pdf-file-compressor": Gift,
  "optimize-pdf-for-print": Printer,

  // Repair & Fix tools
  "repair-pdf": Wrench,
  "fix-pdf": Wrench,
  "recover-pdf-data": HardDrive,
  "repair-corrupt-pdf": Shield,
  "pdf-repair-tool": Hammer,

  // OCR & Extract tools
  "ocr-pdf": Eye,
  "scanned-pdf-to-text": Code,
  "pdf-ocr": Search,
  "searchable-pdf-creator": ZoomIn,
  "ocr-to-word": FileText,
  "ocr-to-excel": FileSpreadsheet,
  "image-to-text": ImageIcon,
  "linearize-pdf": TrendingUp,
  "pdf-fast-web-view": Zap,
  "pdf-optimizer-remove-unused": Eraser,
  "downsample-pdf-images": CircleArrowDown,
  "pdf-font-subsetter": Type,

  // Convert tools
  "word-to-pdf": FileText,
  "doc-to-pdf": FileText,
  "docx-to-pdf": FileText,
  "powerpoint-to-pdf": Presentation,
  "ppt-to-pdf": FileChartColumn,
  "pptx-to-pdf": Presentation,
  "excel-to-pdf": FileSpreadsheet,
  "xls-to-pdf": FileSpreadsheet,
  "xlsx-to-pdf": FileSpreadsheet,
  "jpg-to-pdf": FileImage,
  "png-to-pdf": Image,
  "bmp-to-pdf": Palette,
  "gif-to-pdf": Theater,
  "pdf-to-word": FileOutput,
  "pdf-to-doc": FileOutput,
  "pdf-to-docx": FileOutput,
  "pdf-to-excel": FileOutput,
  "pdf-to-xls": FileOutput,
  "pdf-to-xlsx": FileOutput,
  "pdf-to-powerpoint": FileOutput,
  "pdf-to-ppt": FileOutput,
  "pdf-to-pptx": FileOutput,
  "pdf-to-jpg": FileOutput,
  "pdf-to-png": FileOutput,
  "pdf-to-bmp": FileOutput,
  "pdf-to-gif": FileOutput,
  "pdf-to-tiff": FileOutput,
  "pdf-to-html": Code,
  "pdf-to-xml": FileCode,
  "pdf-to-csv": FileSpreadsheet,
  "pdf-to-txt": FileText,
  "tiff-to-pdf": FileInput,
  "html-to-pdf": FileInput,
  "xml-to-pdf": FileInput,
  "csv-to-pdf": FileInput,
  "txt-to-pdf": FileInput,
  "epub-to-pdf": FileInput,
  "mobi-to-pdf": FileInput,
  "rtf-to-pdf": FileInput,
  "odt-to-pdf": FileInput,
  "ods-to-pdf": FileInput,
  "odp-to-pdf": FileInput,
  "svg-to-pdf": FileInput,
  "webp-to-pdf": FileInput,
  "heic-to-pdf": FileInput,
  "djvu-to-pdf": FileInput,
  "cbr-to-pdf": FileArchive,
  "cbz-to-pdf": FileArchive,
  "ps-to-pdf": FileInput,
  "eps-to-pdf": FileInput,
  "xps-to-pdf": FileInput,
  "oxps-to-pdf": FileInput,

  // Security tools - Encryption
  "protect-pdf": Lock,
  "encrypt-pdf": Lock,
  "secure-pdf": ShieldCheck,
  "password-protect-pdf": Key,
  "add-password-to-pdf": LockOpen,
  "unlock-pdf": Unlock,
  "remove-password-pdf": LockOpen,
  "decrypt-pdf": Unlock,
  "pdf-password-remover": Unlock,
  "protect-pdf-editing": Lock,
  "protect-pdf-printing": Printer,
  "pdf-permissions": FileKey,
  "watermark-protection": Droplet,
  "drm-protection": ShieldAlert,
  "batch-protect-pdf": FolderTree,
  "secure-pdf-sharing": MailCheck,
  "pdf-viewer-protection": EyeOff,
  "pdf-copy-protection": FileLock,
  "restrict-pdf-permissions": Lock,
  
  // Security tools - Signature
  "sign-pdf": Pencil,
  "esign-pdf": FileSignature,
  "digital-signature-pdf": BadgeCheck,
  "electronic-signature": Edit,
  "add-signature-to-pdf": Edit3,
  "certify-pdf": CheckCircle,
  "validate-pdf-signature": ShieldCheck,
  "remove-pdf-signature": X,
  "verify-pdf-signature": ShieldQuestion,
  "timestamp-pdf": AlertCircle,
  "batch-sign-pdf": FolderTree,
  "bulk-esign-pdf": FileSignature,
  "multi-signature-pdf": UserCheck,

  // Security tools - Watermark
  "watermark-pdf": Droplet,
  "text-watermark-pdf": Type,
  "image-watermark-pdf": ImageIcon,
  "diagonal-watermark-pdf": Brush,
  "tiled-watermark-pdf": Layers,
  "transparent-watermark-pdf": Droplets,
  "custom-watermark-pdf": Palette,
  "remove-watermark-pdf": Eraser,
  "batch-watermark-pdf": FolderTree,

  // Security tools - Stamp
  "stamp-pdf": Stamp,
  "confidential-stamp-pdf": ShieldAlert,
  "draft-stamp-pdf": FileEdit,
  "approved-stamp-pdf": CheckCircle,
  "custom-stamp-pdf": Sticker,

  // Edit Pages tools - Page Numbers
  "add-page-numbers": ListOrdered,
  "number-pdf-pages": Hash,
  "custom-page-numbering": Settings,
  "bates-numbering-pdf": Binary,
  "roman-numeral-pages": FileDigit,
  "remove-page-numbers": Eraser,
  
  // Edit Pages tools - Headers & Footers
  "add-header-pdf": ArrowUpCircle,
  "add-footer-pdf": CircleArrowDown,
  "custom-header-footer": Settings,
  "left-aligned-header": AlignLeft,
  "center-aligned-header": AlignCenter,
  "right-aligned-header": AlignRight,
  "remove-header-footer": Eraser,

  // Edit Pages tools - Overlay
  "overlay-pdf": LayoutTemplate,

  // Default icon for any unmapped tools
  default: FileText,
};

export function getToolIcon(toolId: string): LucideIcon {
  return toolIcons[toolId] || toolIcons.default;
}
