import { CalculatorContent } from "@/types";

export const CAP_RATE_CALCULATOR_CONTENT: CalculatorContent = {
  title: "Cap Rate Calculator",
  description: "Calculate the capitalization rate of a real estate investment.",
  category: "Real Estate",
  slug: "cap-rate-calculator",
  article: {
    title: "What is Cap Rate?",
    content: `
    The capitalization rate, or cap rate, is a real estate valuation measure used to compare different real estate investments. It is calculated by dividing the net operating income (NOI) of a property by its current market value.

    ### Formula

    **Cap Rate = Net Operating Income (NOI) / Property Value**

    - **Net Operating Income (NOI):** The annual income generated by a property after deducting all operating expenses, but before deducting debt service and income taxes.
    - **Property Value:** The current market value of the property.

    ### Why is Cap Rate Important?

    Cap rate is a useful metric for quickly assessing the potential return on a real estate investment. A higher cap rate generally indicates a higher potential return, but also potentially higher risk. Conversely, a lower cap rate may indicate lower risk but also a lower return.

    ### How This Calculator Works

    This calculator helps you determine the cap rate of a property by providing the net operating income and the property's market value. The result is expressed as a percentage.
  `,
  },
  calculator: {
    fields: [
      {
        name: "noi",
        label: "Net Operating Income (NOI)",
        type: "number",
        defaultValue: "50000",
      },
      {
        name: "propertyValue",
        label: "Property Value",
        type: "number",
        defaultValue: "1000000",
      },
    ],
    calculate: (values) => {
      const { noi, propertyValue } = values;
      const capRate = (noi / propertyValue) * 100;
      return [{ label: "Cap Rate", value: `${capRate.toFixed(2)}%` }];
    },
  },
};