import { Calculator, Tool } from "@/lib/types";

export const GROSS_RENT_MULTIPLIER_CALCULATOR_CONTENT: Tool = {
  title: "Gross Rent Multiplier Calculator",
  description: "Quickly estimate the value of a rental property using the Gross Rent Multiplier (GRM).",
  category: "Real Estate",
  article: {
    sections: [
      {
        title: "What is the Gross Rent Multiplier (GRM)?",
        content: `
          <p>
            The Gross Rent Multiplier (GRM) is a simple valuation metric used in real estate to compare the value of similar income-producing properties in a given market. It is calculated by dividing the property's price by its gross annual rental income.
          </p>
          <p>
            <strong>GRM = Property Value / Gross Annual Rent</strong>
          </p>
          <p>
            A lower GRM generally indicates a better investment opportunity, as it suggests that the property's price is relatively low compared to its income-generating potential. However, the GRM is a rough measure and does not account for operating expenses, vacancies, or other factors that can affect a property's profitability.
          </p>
        `,
      },
      {
        title: "How to Use the GRM Calculator",
        content: `
          <p>
            To use this calculator, simply enter the property's market value and its gross annual rental income. The calculator will then compute the Gross Rent Multiplier for you.
          </p>
          <ul>
            <li>
              <strong>Property Value:</strong> The market price of the property.
            </li>
            <li>
              <strong>Gross Annual Rent:</strong> The total rental income generated by the property in one year, before deducting any expenses.
            </li>
          </ul>
        `,
      },
    ],
  },
};

export const grossRentMultiplierCalculator: Calculator<any> = {
  ...GROSS_RENT_MULTIPLIER_CALCULATOR_CONTENT,
  calculate: async (data) => {
    const { propertyValue, grossAnnualRent } = data;
    const grossRentMultiplier = grossAnnualRent > 0 ? propertyValue / grossAnnualRent : 0;
    return { grossRentMultiplier };
  },
  inputs: [
    {
      name: "propertyValue",
      label: "Property Value",
      type: "number",
      defaultValue: 500000,
    },
    {
      name: "grossAnnualRent",
      label: "Gross Annual Rent",
      type: "number",
      defaultValue: 60000,
    },
  ],
};