import { CalculatorContent } from '@/types';

export const PREFERRED_EQUITY_VS_COMMON_EQUITY_ANALYZER_CONTENT: CalculatorContent = {
  title: 'Preferred Equity vs. Common Equity Analyzer',
  description: 'Compare preferred equity and common equity returns to determine the best investment structure for your real estate deal.',
  slug: 'preferred-equity-vs-common-equity-analyzer',
  icon: '📊',
  category: 'Investment Analysis',
  article: {
    title: 'Understanding Preferred Equity vs. Common Equity in Real Estate',
    content: `
    <h2>Understanding Preferred Equity vs. Common Equity in Real Estate</h2>
    <p>In real estate investing, equity can be structured in different ways, each with its own risk-return profile. Preferred equity and common equity represent two distinct positions in the capital stack, offering different benefits and risks to investors.</p>
    
    <h3>What is Preferred Equity?</h3>
    <p>Preferred equity is a hybrid investment that sits between senior debt and common equity in the capital stack. It typically offers:</p>
    <ul>
      <li><strong>Fixed Returns:</strong> Preferred equity holders receive a predetermined return (often 8-15% annually)</li>
      <li><strong>Priority in Distributions:</strong> Paid before common equity holders but after debt holders</li>
      <li><strong>Limited Upside:</strong> Usually capped returns with minimal participation in appreciation</li>
      <li><strong>Lower Risk:</strong> More protected than common equity but subordinate to debt</li>
    </ul>

    <h3>What is Common Equity?</h3>
    <p>Common equity represents ownership in the property with full participation in profits and losses:</p>
    <ul>
      <li><strong>Variable Returns:</strong> Returns depend on property performance and appreciation</li>
      <li><strong>Unlimited Upside:</strong> Full participation in property appreciation and profit</li>
      <li><strong>Higher Risk:</strong> Last to receive distributions, first to absorb losses</li>
      <li><strong>Control Rights:</strong> Often includes voting rights and management decisions</li>
    </ul>

    <h3>The Capital Stack</h3>
    <p>A typical real estate capital stack from top to bottom:</p>
    <ol>
      <li><strong>Senior Debt</strong> - First lien mortgage (lowest risk, lowest return)</li>
      <li><strong>Mezzanine Debt</strong> - Subordinated debt (medium-low risk)</li>
      <li><strong>Preferred Equity</strong> - Hybrid position (medium risk, fixed return)</li>
      <li><strong>Common Equity</strong> - Ownership stake (highest risk, highest potential return)</li>
    </ol>

    <h3>How to Use This Analyzer</h3>
    <p>This calculator helps you compare returns between preferred and common equity positions. Input the following:</p>
    <ul>
      <li><strong>Property Value:</strong> Total property acquisition or development cost</li>
      <li><strong>Preferred Equity Amount:</strong> Capital invested as preferred equity</li>
      <li><strong>Preferred Return Rate:</strong> Annual preferred return (typically 8-15%)</li>
      <li><strong>Common Equity Amount:</strong> Capital invested as common equity</li>
      <li><strong>Property Annual NOI:</strong> Net Operating Income generated by the property</li>
      <li><strong>Exit Value:</strong> Expected property value at sale</li>
      <li><strong>Holding Period:</strong> Investment duration in years</li>
    </ul>

    <h3>Key Metrics Calculated</h3>
    <ul>
      <li><strong>Preferred Equity IRR:</strong> Internal rate of return for preferred equity investors</li>
      <li><strong>Common Equity IRR:</strong> Internal rate of return for common equity investors</li>
      <li><strong>Equity Multiple:</strong> Total return as a multiple of initial investment</li>
      <li><strong>Cash-on-Cash Return:</strong> Annual cash return divided by initial investment</li>
      <li><strong>Total Distributions:</strong> Total cash received over the holding period</li>
    </ul>

    <h3>When to Use Preferred Equity</h3>
    <p>Preferred equity makes sense when:</p>
    <ul>
      <li>You want lower risk with predictable returns</li>
      <li>The property has stable cash flows to support distributions</li>
      <li>You prefer income over appreciation potential</li>
      <li>You want priority over common equity but can't get senior debt</li>
    </ul>

    <h3>When to Use Common Equity</h3>
    <p>Common equity is preferred when:</p>
    <ul>
      <li>You believe in significant property appreciation potential</li>
      <li>You're willing to accept higher risk for higher returns</li>
      <li>You want control and decision-making power</li>
      <li>You can afford to wait for returns and handle volatility</li>
    </ul>

    <h3>Tax Considerations</h3>
    <p>Both equity types have different tax implications:</p>
    <ul>
      <li><strong>Preferred Equity:</strong> Returns may be treated as ordinary income or capital gains depending on structure</li>
      <li><strong>Common Equity:</strong> Benefits from depreciation, capital gains treatment, and 1031 exchange eligibility</li>
    </ul>

    <h3>Best Practices</h3>
    <ul>
      <li>Understand your risk tolerance before choosing equity type</li>
      <li>Negotiate preferred return rates based on market conditions</li>
      <li>Review waterfall provisions to understand distribution priorities</li>
      <li>Consider combining both types for balanced portfolio risk</li>
      <li>Evaluate sponsor track record and property fundamentals</li>
      <li>Review legal documents for protective covenants and default provisions</li>
    </ul>
  `,
  },
  calculator: {
    fields: [
      {
        name: 'propertyValue',
        label: 'Property Value',
        type: 'number',
        defaultValue: 5000000,
      },
      {
        name: 'preferredEquity',
        label: 'Preferred Equity Amount',
        type: 'number',
        defaultValue: 1000000,
      },
      {
        name: 'preferredRate',
        label: 'Preferred Return Rate (%)',
        type: 'number',
        defaultValue: 12,
      },
      {
        name: 'commonEquity',
        label: 'Common Equity Amount',
        type: 'number',
        defaultValue: 500000,
      },
      {
        name: 'annualNOI',
        label: 'Annual Net Operating Income',
        type: 'number',
        defaultValue: 400000,
      },
      {
        name: 'exitValue',
        label: 'Expected Exit Value',
        type: 'number',
        defaultValue: 6500000,
      },
      {
        name: 'holdingPeriod',
        label: 'Holding Period (Years)',
        type: 'number',
        defaultValue: 5,
      },
    ],
    results: [
      { label: 'Preferred Equity Annual Return', isCurrency: true },
      { label: 'Preferred Equity Total Return', isCurrency: true },
      { label: 'Preferred Equity IRR', isPercentage: true },
      { label: 'Common Equity Annual Cash Flow', isCurrency: true },
      { label: 'Common Equity Total Return', isCurrency: true },
      { label: 'Common Equity IRR', isPercentage: true },
      { label: 'Preferred Equity Multiple', isText: true },
      { label: 'Common Equity Multiple', isText: true },
    ],
    calculate: (values) => {
      const { propertyValue, preferredEquity, preferredRate, commonEquity, annualNOI, exitValue, holdingPeriod } = values;
      
      const preferredAnnualReturn = preferredEquity * (preferredRate / 100);
      const cashFlowAfterPreferred = annualNOI - preferredAnnualReturn;
      const commonAnnualCashFlow = Math.max(0, cashFlowAfterPreferred);
      
      const totalDebt = propertyValue - preferredEquity - commonEquity;
      const exitProceeds = exitValue - totalDebt;
      
      const preferredTotalPayout = preferredEquity + (preferredAnnualReturn * holdingPeriod);
      const commonExitProceeds = Math.max(0, exitProceeds - preferredTotalPayout);
      const commonTotalCashFlow = (commonAnnualCashFlow * holdingPeriod) + commonExitProceeds;
      
      const preferredIRR = ((Math.pow(preferredTotalPayout / preferredEquity, 1 / holdingPeriod) - 1) * 100);
      const commonIRR = commonTotalCashFlow > 0 ? ((Math.pow(commonTotalCashFlow / commonEquity, 1 / holdingPeriod) - 1) * 100) : 0;
      
      const preferredMultiple = preferredTotalPayout / preferredEquity;
      const commonMultiple = commonTotalCashFlow / commonEquity;

      return [
        { label: 'Preferred Equity Annual Return', value: preferredAnnualReturn.toFixed(2), isCurrency: true },
        { label: 'Preferred Equity Total Return', value: preferredTotalPayout.toFixed(2), isCurrency: true },
        { label: 'Preferred Equity IRR', value: preferredIRR.toFixed(2), isPercentage: true },
        { label: 'Common Equity Annual Cash Flow', value: commonAnnualCashFlow.toFixed(2), isCurrency: true },
        { label: 'Common Equity Total Return', value: commonTotalCashFlow.toFixed(2), isCurrency: true },
        { label: 'Common Equity IRR', value: commonIRR.toFixed(2), isPercentage: true },
        { label: 'Preferred Equity Multiple', value: `${preferredMultiple.toFixed(2)}x`, isText: true },
        { label: 'Common Equity Multiple', value: `${commonMultiple.toFixed(2)}x`, isText: true },
      ];
    },
  },
};
