import { NextResponse } from 'next/server'

const sampleSchools = [
    {
      name: 'Melbourne Grammar School',
      type: 'Secondary',
      sector: 'Independent',
      rating: 4.8,
      enrollment: 1200,
      distance: 2.1,
      address: '355 St Kilda Rd, Melbourne VIC 3004',
      phone: '(03) 9865 7777',
      website: 'www.mgs.vic.edu.au',
      naplanReading: 580,
      naplanNumeracy: 575,
      naplanWriting: 570,
      naplanSpelling: 585,
      naplanGrammar: 580,
      icsea: 1180,
      teacherQualifications: 95,
      studentTeacherRatio: 12,
      specialPrograms: ['IB Program', 'Music Excellence', 'Rowing', 'Debating'],
      facilities: ['Swimming Pool', 'Tennis Courts', 'Science Labs', 'Library', 'Theatre'],
      languages: ['French', 'German', 'Japanese', 'Latin']
    },
    {
      name: 'University High School',
      type: 'Secondary',
      sector: 'Government',
      rating: 4.6,
      enrollment: 1800,
      distance: 3.2,
      address: '77 Story St, Parkville VIC 3052',
      phone: '(03) 9389 0611',
      website: 'www.universityhigh.vic.edu.au',
      naplanReading: 565,
      naplanNumeracy: 560,
      naplanWriting: 555,
      naplanSpelling: 570,
      naplanGrammar: 565,
      icsea: 1150,
      teacherQualifications: 88,
      studentTeacherRatio: 15,
      specialPrograms: ['SEAL Program', 'Music', 'Drama', 'VCE Enhancement'],
      facilities: ['Gymnasium', 'Science Labs', 'Art Studios', 'Library', 'Oval'],
      languages: ['French', 'Italian', 'Japanese']
    },
    {
      name: 'South Melbourne Primary School',
      type: 'Primary',
      sector: 'Government',
      rating: 4.3,
      enrollment: 450,
      distance: 1.8,
      address: '270 Coventry St, South Melbourne VIC 3205',
      phone: '(03) 9699 1423',
      website: 'www.southmelbps.vic.edu.au',
      naplanReading: 520,
      naplanNumeracy: 515,
      naplanWriting: 510,
      naplanSpelling: 525,
      naplanGrammar: 520,
      icsea: 1080,
      teacherQualifications: 85,
      studentTeacherRatio: 18,
      specialPrograms: ['STEM', 'Arts Integration', 'Sustainability'],
      facilities: ['Playground', 'Library', 'Computer Lab', 'Art Room', 'Garden'],
      languages: ['Italian', 'Mandarin']
    },
    {
      name: 'St Michaels Grammar School',
      type: 'Combined',
      sector: 'Independent',
      rating: 4.7,
      enrollment: 1100,
      distance: 4.5,
      address: '25 Chapel St, St Kilda VIC 3182',
      phone: '(03) 9510 9500',
      website: 'www.stmichaels.vic.edu.au',
      naplanReading: 575,
      naplanNumeracy: 570,
      naplanWriting: 565,
      naplanSpelling: 580,
      naplanGrammar: 575,
      icsea: 1160,
      teacherQualifications: 92,
      studentTeacherRatio: 14,
      specialPrograms: ['IB Program', 'Outdoor Education', 'Performing Arts', 'Leadership'],
      facilities: ['Swimming Pool', 'Theatre', 'Science Labs', 'Sports Courts', 'Chapel'],
      languages: ['French', 'Spanish', 'Japanese']
    },
    {
      name: 'Albert Park College',
      type: 'Secondary',
      sector: 'Government',
      rating: 4.2,
      enrollment: 1400,
      distance: 2.8,
      address: '83 Danks St, Albert Park VIC 3206',
      phone: '(03) 8695 9000',
      website: 'www.albertparkcollege.vic.edu.au',
      naplanReading: 545,
      naplanNumeracy: 540,
      naplanWriting: 535,
      naplanSpelling: 550,
      naplanGrammar: 545,
      icsea: 1120,
      teacherQualifications: 82,
      studentTeacherRatio: 16,
      specialPrograms: ['Arts Academy', 'Sports Academy', 'STEM', 'VET Programs'],
      facilities: ['Gymnasium', 'Performing Arts Centre', 'Science Labs', 'Sports Fields'],
      languages: ['French', 'Italian']
    }
  ]

export async function GET() {
  return NextResponse.json(sampleSchools)
}